<div class="profile_index">

	<div class="well">
		<div class="row">
			<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
				<?php if ($this->_currentUser->getId() === $this->user->getId()): ?>
				<div class="portrait" id="croppic-area" style="width: 200px; height: 200px; position: relative; overflow: hidden;">
				<?php endif; ?>
					<img style="width: 200px; height: 200px;" src="/file/?file=<?= $this->user->getPortraitFileId(); ?>" />
				<?php if ($this->_currentUser->getId() === $this->user->getId()): ?>
				</div>
				<?php endif; ?>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 profile_information">
				<span class="name"><?= $this->escape($this->user->getFirstName() . ' ' . $this->user->getLastName()); ?></span>
				<p>
					<?= $this->_('user_department'); ?>:
					<span id="profile_department"><?= $this->escape($this->user->getDepartment()); ?></span>
					<?php if ($this->_currentUser->getId() === $this->user->getId()): ?>
					<a href="#" class="profile_update_property" data-property="department"><i class="fa fa-edit"></i></a>
					<?php endif; ?>
				<?php if ($this->_currentUser->getId() === $this->user->getId()): ?>
					<br>
					<?= $this->_('profile_language'); ?>:
					<span id="profile_current_language"><?= $this->_('language_' . $this->_currentUser->getLanguage()); ?> <a href="#" id="profile_edit_language"><i class="fa fa-edit"></i></a></span>
					<span id="profile_change_language" style="display: none;">
						<select id="profile_new_language">
							<option value="en"<?= ($this->_currentUser->getLanguage() == 'en') ? ' selected="selected"' : ''; ?>><?= $this->_('language_en'); ?></option>
							<option value="de"<?= ($this->_currentUser->getLanguage() == 'de') ? ' selected="selected"' : ''; ?>><?= $this->_('language_de'); ?></option>
						</select>
					</span>
				<?php endif; ?>
				</p>

				<?php if ($this->_currentUser->getId() !== $this->user->getId()): ?>
					<?php

					$relation = $this->_currentUser->getRelationTo($this->user);

					if ($relation === null): ?>
						<a href="#" class="btn btn-primary add_request" data-id="<?= $this->user->getId(); ?>">
							<i class="fa fa-user"></i> <?= $this->_('relation_send_request'); ?>
						</a>
					<?php elseif (!$relation->getConfirmed() && $relation->getUserId2() === $this->user->getId()): ?>
						<a href="#" class="btn btn-primary">
							<i class="fa fa-clock-o"></i> <?= $this->_('relation_request_pending'); ?>
						</a>
					<?php elseif (!$relation->getConfirmed() && $relation->getUserId2() === $this->_currentUser->getId()): ?>
						<div class="btn-group">
							<button type="button" data-id="<?= $this->user->getId(); ?>" class="btn btn-primary accept_request"><i class="fa fa-check"></i> <?= $this->_('btn_accept'); ?></button>
							<button type="button" data-id="<?= $this->user->getId(); ?>" class="btn btn-default decline_request"><i class="fa fa-times"></i> <?= $this->_('btn_decline'); ?></button>
						</div>
					<?php else: ?>
						<button class="btn btn-default">
							<i class="fa fa-thumbs-o-up"></i> Confirmed
						</button>
					<?php endif; ?>
				<?php endif; ?>
			</div>
		</div>
	</div>

</div>

<?php if ($this->_currentUser->getId() === $this->user->getId()): ?>
<script type="text/javascript">
	$(function() {

		$('#profile_edit_language').click(function(event) {

			event.preventDefault();

			$('#profile_current_language').hide();
			$('#profile_change_language').show();

			$('#profile_new_language').change(function(event) {

				var newLanguage = $(this).val();

				$.ajax({
					method: 'post',
					url: '/profile/change-language/',
					data: {
						language: newLanguage
					},
					dataType: 'json',
					success: function(result) {
						if (result.success == true) {
							location.reload();
						}
					}
				});

			});

		});

		$('.profile_update_property').click(function(event) {

			event.preventDefault();

			$('.profile_update_property').hide();

			var property = $(this).data('property');
			var field = $('#profile_' + property);
			var currentValue = field.html();

			field.html($('<input type="text" id="profile_' + property + '_input" value="' + currentValue + '" />'));

			var saveButton = $('<a href="#"><i class="fa fa-save"></i></a>');

			saveButton.appendTo($(field));

			var cancelButton = $('<a href="#"><i class="fa fa-times"></i></a>');

			cancelButton.appendTo($(field));

			$(cancelButton).click(function(event) {

				event.preventDefault();

				field.text(currentValue);
				$('.profile_update_property').show();

			});

			$(saveButton).click(function(event) {

				event.preventDefault();

				var newValue = $('#profile_' + property + '_input').val();

				$.ajax({
					method: 'post',
					url: '/profile/update/',
					data: {
						key: property,
						value: newValue
					},
					dataType: 'json',
					success: function(result) {
						if (result.success == true) {
							$(field).text(newValue);
							$('.profile_update_property').show();
						}
					}
				});

			});

		});

		var croppicContainerModalOptions = {
			uploadUrl: '/profile/save-pic/',
			cropUrl: '/profile/crop-pic/',
			modal: true,
			imgEyecandyOpacity:0.4,
			loaderHtml:'<div class="loader bubblingG"><span id="bubblingG_1"></span><span id="bubblingG_2"></span><span id="bubblingG_3"></span></div> '
		};

		var cropContainerModal = new Croppic('croppic-area', croppicContainerModalOptions);
	});
</script>
<?php endif; ?>