<div class="profile_index">

	<div class="row">
		<div class="col-xs-12 col-sm-5 col-md-5 col-lg-5">
			<?php if ($this->_currentUser->getId() === $this->user->getId()): ?>
			<div class="portait" id="croppic-area" style="width: 200px; height: 200px; position: relative;">
			<?php endif; ?>
				<img style="width: 200px; height: 200px;" src="/file/?file=<?= $this->user->getPortraitFileId(); ?>" />
			<?php if ($this->_currentUser->getId() === $this->user->getId()): ?>
			</div>
			<?php endif; ?>
		</div>
		<div class="col-xs-12 col-sm-7 col-md-7 col-lg-7">
			<h2><?= $this->escape($this->user->getFirstName() . ' ' . $this->user->getLastName()); ?></h2>
			<p>
				<small>Department: <?= $this->escape($this->user->getDepartment()); ?></small>
			</p>

			<?php if ($this->_currentUser->getId() !== $this->user->getId()): ?>
				<p>
				<?php

				$relation = $this->_currentUser->getRelationTo($this->user);

				if ($relation === null): ?>
					<a href="#" class="btn btn-primary add_request" data-id="<?= $this->user->getId(); ?>">
						<i class="fa fa-user"></i> Send contact request
					</a>
				<?php elseif (!$relation->getConfirmed() && $relation->getUserId2() === $this->user->getId()): ?>
					<a href="#" class="btn btn-primary">
						<i class="fa fa-clock-o"></i> Request pending...
					</a>
				<?php elseif (!$relation->getConfirmed() && $relation->getUserId2() === $this->_currentUser->getId()): ?>
					<div class="btn-group">
						<button type="button" data-id="<?= $this->user->getId(); ?>" class="btn btn-primary accept_request"><i class="fa fa-check"></i> Accept</button>
						<button type="button" data-id="<?= $this->user->getId(); ?>" class="btn btn-default decline_request"><i class="fa fa-times"></i> Decline</button>
					</div>
				<?php else: ?>
					<button class="btn btn-default">
						<i class="fa fa-thumbs-o-up"></i> Confirmed
					</button>
				<?php endif; ?>
				</p>
			<?php endif; ?>
		</div>
	</div>

</div>

<?php if ($this->_currentUser->getId() === $this->user->getId()): ?>
<script type="text/javascript">
	$(function() {
		var croppicContainerModalOptions = {
			uploadUrl: '/profile/save-pic/',
			cropUrl: '/profile/crop-pic/',
			modal: true,
			imgEyecandyOpacity:0.4,
			loaderHtml:'<div class="loader bubblingG"><span id="bubblingG_1"></span><span id="bubblingG_2"></span><span id="bubblingG_3"></span></div> '
		};

		var cropContainerModal = new Croppic('croppic-area', croppicContainerModalOptions);
	});
</script>
<?php endif; ?>