<form role="form" action="" method="post">

	<legend><?= $this->_('registration_title'); ?></legend>

	<div class="form-group">
		<?= $this->displayMessage(@$this->errors['email']); ?>
		<input type="email" class="form-control" name="email" value="<?= $this->escape($this->email); ?>" placeholder="<?= $this->_('registration_placeholder_email'); ?>">
	</div>

	<div class="form-group">
		<?= $this->displayMessage(@$this->errors['first_name']); ?>
		<input type="text" class="form-control" name="first_name" value="<?= $this->escape($this->firstName); ?>" placeholder="<?= $this->_('registration_placeholder_first_name'); ?>">
	</div>

	<div class="form-group">
		<?= $this->displayMessage(@$this->errors['last_name']); ?>
		<input type="text" class="form-control" name="last_name" value="<?= $this->escape($this->lastName); ?>" placeholder="<?= $this->_('registration_placeholder_last_name'); ?>">
	</div>

	<div class="form-group">
		<?= $this->displayMessage(@$this->errors['password']); ?>
		<input type="password" class="form-control" name="password" value="" placeholder="<?= $this->_('registration_placeholder_password'); ?>">
	</div>

	<div class="form-group">
		<?= $this->displayMessage(@$this->errors['password2']); ?>
		<input type="password" class="form-control" name="password2" value="" placeholder="<?= $this->_('registration_placeholder_password2'); ?>">
	</div>

	<div class="form-group">
		<?= $this->displayMessage(@$this->errors['language']); ?>
		<select class="form-control" name="language">
			<option value="en"<?= ($this->language == 'en' || (!$this->language && $defaultLanguage == 'en')) ? ' selected="selected"' : ''; ?>><?= $this->_('language_en'); ?></option>
			<option value="de"<?= ($this->language == 'de' || (!$this->language && $defaultLanguage == 'de')) ? ' selected="selected"' : ''; ?>><?= $this->_('language_de'); ?></option>
		</select>
	</div>

	<div class="form-group" style="text-align: center;">
		<input type="submit" class="btn btn-primary" value="<?= $this->_('registration_btn_register'); ?>" />
	</div>

</form>