<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title><?= $this->escape($this->_config['site_title']['value']); ?></title>

	<link href="/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
	<link href="/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet">
	<link href="/bower_components/croppic/assets/css/croppic.css" rel="stylesheet">
	<link href="/css/style.css" rel="stylesheet">

	<script type="text/javascript" src="/bower_components/jquery/dist/jquery.min.js"></script>
	<script type="text/javascript" src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
	<script tpye="text/javascript" src="/bower_components/croppic/croppic.min.js"></script>
	<script type="text/javascript" src="/js/index/index.js"></script>

	<script type="text/javascript">

		var currentUserId = <?= json_encode(($this->_currentUser) ? $this->_currentUser->getId() : null); ?>;

	</script>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">

		<a class="navbar-brand" href="/"><?= $this->escape($this->_config['site_title']['value']); ?></a>

		<?php if ($this->_currentUser): ?>

		<form class="navbar-form navbar-left" role="search" action="/search/" method="post">
			<div class="form-group">
				<input type="text" class="form-control" name="search" placeholder="Search">
			</div>
			<button type="submit" class="btn btn-default"><i class="fa fa-search"></i> Search</button>
		</form>

		<ul class="nav navbar-nav navbar-right">
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-th-list"></span> <span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu">
					<li><a href="/profile/me/">My profile</a></li>
					<li class="divider"></li>
					<li><a href="/index/logout/">Logout</a></li>
				</ul>
			</li>
		</ul>

		<p class="navbar-text navbar-right">Signed in as <a href="/profile/me/"><?= $this->escape($this->_currentUser->getFirstName() . ' ' . $this->_currentUser->getLastName()); ?></a></p>

		<?php else: ?>

		<form class="navbar-form form-inline pull-right" role="form" method="post" action="/index/login">
			<div class="form-group">
				<label class="sr-only" for="email">Email address</label>
				<input name="email" type="email" class="form-control" id="email" placeholder="Enter email">
			</div>
			<div class="form-group">
				<label class="sr-only" for="password">Password</label>
				<input name="password" type="password" class="form-control" id="password" placeholder="Password">
			</div>
			<button type="submit" class="btn btn-default">Sign in</button>
		</form>

		<?php endif; ?>

	</div>
</nav>

<div class="container">
	<div class="row">

		<div class="col-md-3 col-lg-3">
			<?php if ($this->_currentUser): ?>
			<div class="well">
				<div id="left_box">

					<a href="/profile/me/"><?= $this->escape($this->_currentUser->getFirstName() . ' ' . $this->_currentUser->getLastName()); ?></a>

					<div class="groups">
						<ul>
							<li><a href="#" class="add-group-dialog">Neue Gruppe</a></li>
							<?php if ($groups = $this->_currentUser->getGroups()): ?>
								<?php foreach ($groups as $group): ?>
									<li><a href="/group/?id=<?= $group->getId(); ?>"><?= $this->escape($group->getName()); ?></a></li>
								<?php endforeach; ?>
							<?php endif; ?>
						</ul>
					</div>
				</div>
			</div>
			<?php endif; ?>
		</div>

		<div class="col-md-6 col-lg-6">
			<?= $html; ?>
		</div>

		<div class="col-md-3 col-lg-3">
			<?php if ($this->_currentUser): ?>
			<div class="well">
				<?php if ($contacts = $this->_currentUser->getUnconfirmedContacts()): ?>
					<div class="unconfirmed_contacts">
						<p class="headline">CONTACT REQUESTS</p>
						<?php foreach ($contacts as $contact): ?>
							<div class="unconfirmed_contact">
								<img class="portrait" src="/file/?file=<?= $contact->getPortraitFileId(); ?>" />
								<?= $this->escape($contact->getFirstName() . ' ' . $contact->getLastName()); ?>
								<br />
								<div class="btn-group">
									<a href="#" class="btn btn-primary btn-sm accept_request" data-id="<?= $contact->getId(); ?>">Accept</a>
									<a href="#" class="btn btn-default btn-sm decline_request" data-id="<?= $contact->getId(); ?>">Decline</a>
								</div>
							</div>
						<?php endforeach; ?>
					</div>
				<?php endif; ?>
				<?php if ($this->_currentUser->getType() === 'admin' && $this->_unconfirmedUsers): ?>
					<div class="unconfirmed_users">
						<p class="headline">REGISTRATION REQUESTS</p>
						<?php foreach ($this->_unconfirmedUsers as $user): ?>
							<div class="unconfirmed_user">
								<div class="col-sm-4">
									<img class="img-responsive" src="/file/?file=<?= $user->getPortraitFileId(); ?>" />
								</div>
								<div class="col-sm-6">
									<?= $this->escape($user->getFirstName() . ' ' . $user->getLastName()); ?><br>
									<small><?= $this->escape($user->getEmail()); ?></small>
								</div>
								<br />
								<div class="btn-group">
									<a href="#" class="btn btn-primary btn-sm accept_user" data-id="<?= $user->getId(); ?>">Accept</a>
									<a href="#" class="btn btn-default btn-sm decline_user" data-id="<?= $user->getId(); ?>">Decline</a>
								</div>
							</div>
						<?php endforeach; ?>
					</div>
				<?php endif; ?>
			</div>
			<?php endif; ?>
		</div>
	</div>
</div>


</body>
</html>