<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title><?= $this->escape($this->_config['site_title']['value']); ?></title>

	<link href="/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
	<link href="/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet">
	<link href="/bower_components/croppic/assets/css/croppic.css" rel="stylesheet">
	<link href="//cdn.jsdelivr.net/emojione/1.3.0/assets/css/emojione.min.css" rel="stylesheet">
	<link href="/css/style.css" rel="stylesheet">

	<script type="text/javascript" src="/bower_components/jquery/dist/jquery.min.js"></script>
	<script type="text/javascript" src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="/bower_components/croppic/croppic.min.js"></script>
	<script type="text/javascript" src="//cdn.jsdelivr.net/emojione/1.3.0/lib/js/emojione.min.js"></script>
	<script type="text/javascript" src="/js/global.js"></script>

	<?php if ($this->_js): ?>
	<script type="text/javascript" src="<?= $this->escape($this->_js); ?>"></script>
	<?php endif; ?>

	<script type="text/javascript">

		var currentUserId = <?= json_encode(($this->_currentUser) ? $this->_currentUser->getId() : null); ?>;

		var globalTranslations = {
			post_like: <?= json_encode($this->_('post_like')); ?>,
			post_dislike: <?= json_encode($this->_('post_dislike')); ?>,
			post_comments: <?= json_encode($this->_('post_comments')); ?>,
			post_comments_write_comment: <?= json_encode($this->_('post_comments_write_comment')); ?>,
			post_comments_write_comment_send: <?= json_encode($this->_('post_comments_write_comment_send')); ?>
		};

	</script>
</head>
<body>

<nav id="main-navigation" class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">

		<a class="navbar-brand" href="/"><?= $this->escape($this->_config['site_title']['value']); ?></a>

		<?php if ($this->_currentUser): ?>

		<form class="navbar-form navbar-left" role="search" action="/search/" method="post">
			<div class="form-group">
				<input type="text" class="form-control" name="search" placeholder="<?= $this->_('search_placeholder_search'); ?>">
			</div>
			<button type="submit" class="btn btn-default"><i class="fa fa-search"></i> <?= $this->_('search_btn_search'); ?></button>
		</form>

		<ul class="nav navbar-nav navbar-right">
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-th-list"></span> <span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu">
					<li><a href="/profile/me/"><?= $this->_('top_navigation_my_profile'); ?></a></li>
					<li class="divider"></li>
					<li><a href="/index/logout/"><?= $this->_('top_navigation_logout'); ?></a></li>
				</ul>
			</li>
		</ul>

		<p class="navbar-text navbar-right"><?= $this->_('top_navigation_logged_in_as'); ?> <a href="/profile/me/"><?= $this->escape($this->_currentUser->getFirstName() . ' ' . $this->_currentUser->getLastName()); ?></a></p>

		<ul class="nav navbar-nav navbar-right">
			<li class="conversation-icon"><a href="/conversation/"><i class="fa fa-envelope"></i><?php if ($this->getUnreadConversationPostCount() > 0): ?> <span class="badge"><?= $this->escape($this->getUnreadConversationPostCount()); ?></span><?php endif; ?></a></li>
		</ul>

		<?php else: ?>

		<form class="navbar-form form-inline pull-right" role="form" method="post" action="/index/login">
			<div class="form-group">
				<label class="sr-only" for="email"><?= $this->_('top_navigation_login_email'); ?></label>
				<input name="email" type="email" class="form-control" id="email" placeholder="<?= $this->_('top_navigation_login_email'); ?>">
			</div>
			<div class="form-group">
				<label class="sr-only" for="password"><?= $this->_('top_navigation_login_password'); ?></label>
				<input name="password" type="password" class="form-control" id="password" placeholder="<?= $this->_('top_navigation_login_password'); ?>">
			</div>
			<button type="submit" class="btn btn-default"><?= $this->_('top_navigation_login_btn_login'); ?></button>
		</form>

		<?php endif; ?>

	</div>
</nav>

<div class="container">
	<div class="row">

		<?php if (!$this->hideLeftColumn): ?>
		<div class="col-md-3 col-lg-3">
			<?php if ($this->_currentUser): ?>
			<div class="well">
				<div id="left_box">

					<a href="/profile/me/"><?= $this->escape($this->_currentUser->getFirstName() . ' ' . $this->_currentUser->getLastName()); ?></a>

					<div class="groups">
						<ul>
							<li><a href="#" data-toggle="modal" data-target="#group_add_modal"><?= $this->_('navigation_add_group'); ?></a></li>
							<?php if ($groups = $this->_currentUser->getGroups()): ?>
								<?php foreach ($groups as $group): ?>
									<li><a href="/group/?id=<?= $group->getId(); ?>"><?= $this->escape($group->getName()); ?></a></li>
								<?php endforeach; ?>
							<?php endif; ?>
						</ul>
					</div>
				</div>
			</div>
			<?php endif; ?>
		</div>
		<?php endif; ?>

		<div class="<?= ($this->middleColumnClasses) ? $this->middleColumnClasses : 'col-md-6 col-lg-6'; ?>">
			<?= $html; ?>
		</div>

		<?php if (!$this->hideRightColumn): ?>
		<div class="col-md-3 col-lg-3">
			<?php if ($this->_currentUser): ?>
			<div class="well">
				<?php if ($contacts = $this->_currentUser->getUnconfirmedContacts()): ?>
					<div class="unconfirmed_contacts">
						<p class="headline"><?= $this->_('contact_requests_title'); ?></p>
						<?php foreach ($contacts as $contact): ?>
							<div class="unconfirmed_contact">
								<img class="portrait" src="/file/?file=<?= $contact->getPortraitFileId(); ?>" />
								<?= $this->escape($contact->getFirstName() . ' ' . $contact->getLastName()); ?>
								<br />
								<div class="btn-group">
									<a href="#" class="btn btn-primary btn-sm accept_request" data-id="<?= $contact->getId(); ?>"><?= $this->_('btn_accept'); ?></a>
									<a href="#" class="btn btn-default btn-sm decline_request" data-id="<?= $contact->getId(); ?>"><?= $this->_('btn_decline'); ?></a>
								</div>
							</div>
						<?php endforeach; ?>
					</div>
				<?php endif; ?>
				<?php if ($groupInvitations = $this->_currentUser->getGroupInvitations()): ?>
					<div class="group_invitations">
						<p class="headline"><?= $this->_('group_requests_title'); ?></p>
						<?php foreach ($groupInvitations as $group): ?>
							<div class="group_invitation">
								<img class="portrait" src="/file/?file=<?= $group->getPortraitFileId(); ?>" />
								<?= $this->escape($group->getName()); ?>
								<br />
								<div class="btn-group">
									<a href="#" class="btn btn-primary btn-sm accept_group_request" data-id="<?= $group->getId(); ?>"><?= $this->_('btn_accept'); ?></a>
									<a href="#" class="btn btn-default btn-sm decline_group_request" data-id="<?= $group->getId(); ?>"><?= $this->_('btn_decline'); ?></a>
								</div>
							</div>
						<?php endforeach; ?>
					</div>
				<?php endif; ?>
				<?php if ($this->_currentUser->getType() === 'admin' && $this->_unconfirmedUsers): ?>
					<div class="unconfirmed_users">
						<p class="headline"><?= $this->_('registration_requests_title'); ?></p>
						<?php foreach ($this->_unconfirmedUsers as $user): ?>
							<div class="unconfirmed_user">
								<div class="col-sm-4">
									<img class="img-responsive" src="/file/?file=<?= $user->getPortraitFileId(); ?>" />
								</div>
								<div class="col-sm-6">
									<?= $this->escape($user->getFirstName() . ' ' . $user->getLastName()); ?><br>
									<small><?= $this->escape($user->getEmail()); ?></small>
								</div>
								<br />
								<div class="btn-group">
									<a href="#" class="btn btn-primary btn-sm accept_user" data-id="<?= $user->getId(); ?>"><?= $this->_('btn_accept'); ?></a>
									<a href="#" class="btn btn-default btn-sm decline_user" data-id="<?= $user->getId(); ?>"><?= $this->_('btn_decline'); ?></a>
								</div>
							</div>
						<?php endforeach; ?>
					</div>
				<?php endif; ?>
			</div>
			<?php endif; ?>
		</div>
		<?php endif; ?>
	</div>
</div>

<div class="modal fade" id="group_add_modal" role="dialog" aria-labelledby="group_modal_title" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"><?= $this->_('btn_close'); ?></span></button>
				<h4 class="modal-title" id="group_modal_title"><?= $this->_('group_add_popup_title'); ?></h4>
			</div>
			<div class="modal-body">
				<form role="form">

					<div class="form-group">
						<input type="text" class="form-control" id="group_name" value="" placeholder="<?= $this->_('group_add_input_name_placeholder'); ?>" />
					</div>

					<div class="form-group">
						<textarea class="form-control" id="group_description" placeholder="<?= $this->_('group_add_input_description_placeholder'); ?>"></textarea>
					</div>

					<div class="form-group">
						<select id="group_type" class="form-control">
							<option value="hidden"><?= $this->_('group_type_hidden'); ?></option>
							<option value="protected"><?= $this->_('group_type_protected'); ?></option>
							<option value="public"><?= $this->_('group_type_public'); ?></option>
						</select>
					</div>

				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal"><?= $this->_('btn_cancel'); ?></button>
				<button type="button" class="btn btn-primary" id="action_add_group"><?= $this->translator->_('group_add_btn_add'); ?></button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

</body>
</html>