<div class="index_index">

	<div id="create_post">

		<form id="create_post_form" role="form">

			<div class="form-group">
				<textarea id="post_content" class="form-control" name="content" placeholder="What's on your mind?"></textarea>
			</div>

			<div class="form-group" style="text-align: right;">
				<input type="submit" class="btn btn-primary" value="Post" />
			</div>

		</form>

	</div>

	<div class="posts">

		<!-- -->

	</div>

</div>