<div class="index_login">

		<form class="form-signin" role="form" method="post">

			<h2 class="form-signin-heading"><?= $this->escape($this->_config['site_title']['value']); ?></h2>
			<h3 class="form-signin-subheading">Please sign in</h3>

			<input name="email" type="email" class="form-control" placeholder="Email address" required autofocus>

			<input name="password" type="password" class="form-control" placeholder="Password" required>

			<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
			
		</form>

</div>