<div class="index_login">

	<div class="login">

		<form method="post" action="">

			<div class="email">
				<input type="text" name="email" placeholder="Your e-mail-address" />
			</div>

			<div class="password">
				<input type="password" name="password" placeholder="Your password" />
			</div>

			<div class="submit">
				<input type="submit" value="Login" />
			</div>

		</form>

	</div>

</div>