<div class="block" id="search">

	<div class="well">
		<h3><?= $this->_('search_users_title'); ?></h3>
	<?php if ($this->users): ?>
		<?php foreach ($this->users as $user): ?>
		<div class="row list-group-item">
			<div class="col-xs-3">
				<a href="/profile/?user=<?= $user->getId(); ?>">
					<img style="width: 80px; height: 80px;" src="/file/?file=<?= $user->getPortraitFileId(); ?>" />
				</a>
			</div>
			<div class="col-xs-9">
				<a href="/profile/?user=<?= $user->getId(); ?>">
					<h4 class="list-group-item-heading"><?= $this->escape($user->getFirstName() . ' ' . $user->getLastName()); ?></h4>
				</a>
				<?php if ($user->getDepartment()): ?>
				<p class="list-group-item-text">
					<small><?= $this->_('user_department'); ?>: <?= $this->escape($user->getDepartment()); ?></small>
				</p>
				<?php endif; ?>
			</div>
		</div>
		<?php endforeach; ?>
	<?php else: ?>
		<p><?= $this->_('search_users_msg_no_result'); ?></p>
	<?php endif; ?>
	</div>

	<div class="well">
		<h3><?= $this->_('search_groups_title'); ?></h3>

		<?php if ($this->groups): ?>

		<?php foreach ($this->groups as $group): ?>
			<div class="row list-group-item">
				<div class="col-xs-3">
					<a href="/group/?id=<?= $group->getId(); ?>">
						<img style="width: 80px; height: 80px;" src="/file/?file=<?= $group->getPortraitFileId(); ?>" />
					</a>
				</div>
				<div class="col-xs-9">
					<a href="/group/?id=<?= $group->getId(); ?>">
						<h4 class="list-group-item-heading"><?= $this->escape($group->getName()); ?></h4>
					</a>
					<p class="list-group-item-text">
						<small><?= $this->escape($group->getDescription()); ?></small>
					</p>
				</div>
			</div>
		<?php endforeach; ?>

		<?php else: ?>

		<p><?= $this->_('search_groups_msg_no_result'); ?></p>

		<?php endif; ?>

	</div>
</div>